version: '3.1'

services:
  database:
    container_name: firebird
    image: jacobalberty/firebird:2.5.8-sc
    ports:
      - ${PORT-3050}:3050
    environment:
      - ISC_PASSWORD=${ISC_PASSWORD-masterkey}
      - TZ=${TZ-America/Sao_Paulo}
    volumes:
      - data:/firebird
      - ./files2docker/scripts:/scripts
      - ./files2docker/tbudf.so:/usr/local/firebird/UDF/tbudf.so
      - ${EXTERNAL_SCRIPTS-./files2docker/external_scripts}:/external_scripts
      - ./files2docker/docker-entrypoint.sh:/usr/local/firebird/docker-entrypoint.sh
      - ${DATABASES_PATH-./files2docker/databases}:/firebird/data
    restart: unless-stopped

volumes:
  data:
